### ISSUE TITLE
<Error>: CGContextDrawImage: invalid context 0x0

### ISSUE THREAD

**Issue by sanshanchuns** [rs/SDWebImage#1454]
when i invoked methods below, I got errors as following.
sd_setImageWithURL
downloadImageWithURL

<Error>: CGContextDrawImage: invalid context 0x0.
<Error>: CGBitmapContextCreateImage: invalid context 0x0

**Comment by sanshanchuns** [comment]
SDWebImage (3.7.5):
    - SDWebImage/Core (= 3.7.5)

**Comment by sanshanchuns** [comment]
platform ios9 ios8  xcode7.2

**Comment by sanshanchuns** [comment]
plus:

<Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable
<Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable

**Comment by mythodeia** [comment]
@sanshanchuns this warning is normally coming from `SDWebImageDecoder.m` file
can you post some images that produce this issue?

**Comment by juyka** [comment]
@mythodeia I got the same problem with image http://l-userpic.livejournal.com/125411728/70934036

**Comment by mythodeia** [comment]
@juyka this is the full console warning for your url:
```
CGBitmapContextCreate: unsupported parameter combination:
	 	16 integer bits/component;
	 	64 bits/pixel;
		RGB color space model; kCGImageAlphaPremultipliedFirst;
		768 bytes/row.
	Valid parameters for RGB color space model are:
		16  bits per pixel,		 5  bits per component,		 kCGImageAlphaNoneSkipFirst
		32  bits per pixel,		 8  bits per component,		 kCGImageAlphaNoneSkipFirst
		32  bits per pixel,		 8  bits per component,		 kCGImageAlphaNoneSkipLast
		32  bits per pixel,		 8  bits per component,		 kCGImageAlphaPremultipliedFirst
		32  bits per pixel,		 8  bits per component,		 kCGImageAlphaPremultipliedLast
		64  bits per pixel,		 16 bits per component,		 kCGImageAlphaPremultipliedLast
		64  bits per pixel,		 16 bits per component,		 kCGImageAlphaNoneSkipLast
		128 bits per pixel,		 32 bits per component,		 kCGImageAlphaNoneSkipLast |kCGBitmapFloatComponents
		128 bits per pixel,		 32 bits per component,		 kCGImageAlphaPremultipliedLast |kCGBitmapFloatComponents
```
check [this](https://github.com/rs/SDWebImage/issues/1401#issuecomment-171201846) for supported contexts

**Comment by caldofran** [comment]
I am having the same issue with version 3.7.5. Downloading the same image on version 3.7.3 worked without problems.
This is the image: https://s3.amazonaws.com/jobandtalent_production/assets/default_logos/logo.large.N.2D8D2B.png

And I get the same error as @juyka:

```
CGBitmapContextCreate: unsupported parameter combination:
	 	16 integer bits/component;
	 	64 bits/pixel;
		RGB color space model; kCGImageAlphaPremultipliedFirst;
		1184 bytes/row.
	Valid parameters for RGB color space model are:
		16  bits per pixel,		 5  bits per component,		 kCGImageAlphaNoneSkipFirst
		32  bits per pixel,		 8  bits per component,		 kCGImageAlphaNoneSkipFirst
		32  bits per pixel,		 8  bits per component,		 kCGImageAlphaNoneSkipLast
		32  bits per pixel,		 8  bits per component,		 kCGImageAlphaPremultipliedFirst
		32  bits per pixel,		 8  bits per component,		 kCGImageAlphaPremultipliedLast
		64  bits per pixel,		 16 bits per component,		 kCGImageAlphaPremultipliedLast
		64  bits per pixel,		 16 bits per component,		 kCGImageAlphaNoneSkipLast
		128 bits per pixel,		 32 bits per component,		 kCGImageAlphaNoneSkipLast |kCGBitmapFloatComponents
		128 bits per pixel,		 32 bits per component,		 kCGImageAlphaPremultipliedLast |kCGBitmapFloatComponents
	See Quartz 2D Programming Guide (available online) for more information.
```

**Comment by mythodeia** [comment]
as i have said before replacing the CGImageGetBitsPerComponent(imageRef) with 8 [here](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageDecoder.m#L49) will make these images only work, but generate warnings for others.
a working solution would be to check if the bits per component result in an unsupported combination and if it does then roll back to the hardcoded 8.

**Comment by nejra** [comment]
I have the same issue and I fixed it by downgrading to 3.7.3 version, as @caldofran suggested. Hopefully it will be fixed in the future.

**Comment by pljhonglu** [comment]
I have the same problem.

`CGImageGetBitsPerComponent` result is 16, and the context is 0x0.

I have the same opinion as @mythodeia . check if the bits per component result in an unsupported combination and if it does then roll back to the original image.

**Comment by mythodeia** [comment]
@caldofran @sanshanchuns @pljhonglu can you try this pull and let me know if that works for you
https://github.com/rs/SDWebImage/pull/1496

**Comment by pljhonglu** [comment]
@mythodeia it works for me. Thanks!

**Comment by mythodeia** [comment]
fixed https://github.com/rs/SDWebImage/pull/1496

**Comment by sunilsharma08** [comment]
I am also getting the same error. I tried latest version but error is still appearing.
I tried to replicate in demo project by adding in array image url "http://staging.theooru.com/uploads/star/profile_image/4/Screen_Shot_2016-02-19_at_5.19.01_PM.png"
Error displayed are : "**<Error>: CGContextDrawImage: invalid context 0x0.**"
and "**<Error>: CGBitmapContextCreateImage: invalid context 0x0.**"

**Comment by mythodeia** [comment]
@sunilsharma08 this happens because the image that gets downloaded is nil.

**Comment by sunilsharma08** [comment]
Is it possible to handle such situtation by library like if image downloaded is nil then I can avoid this error

**Comment by mythodeia** [comment]
you can add something like this ```if (image == nil) { return nil; }``` at the top of the ```decodedImageWithImage``` method in ```SDWebImageDecoder.m``` file

**Comment by sunilsharma08** [comment]
Thanks, now everything is working fine.

**Comment by venky284** [comment]
@mythodeia  I use this for my Xamarin project as a component. How could I get this fix?

**Comment by mythodeia** [comment]
its not in a release yet. we have added it to the 3.7.6 release

**Comment by venky284** [comment]
@mythodeia  Any Estimated date for Xamarin 3.7.6 release?

**Comment by mythodeia** [comment]
@venky284 sorry i cannot make any estimations as i am a bit swamped at work
