### ISSUE TITLE
SDWebImage 4.0.0

### ISSUE THREAD

**Issue by bpoplauschi** [rs/SDWebImage#1692]
### List of tickets
- [Issues and Pull Requests](https://github.com/rs/SDWebImage/milestone/3)
### Releases
- [4.0.0-beta](https://github.com/rs/SDWebImage/releases/tag/4.0.0-beta)
- [4.0.0-beta2](https://github.com/rs/SDWebImage/releases/tag/4.0.0-beta2)
- ...
### List of changes
- watchOS, OS X
- modern ObjC (`instancetype`, `NS_DESIGNATED_INITIALIZER`, Lightweight Generics, Nullability)
- FLAnimatedImage integration
- unit tests coverage from 35% to 70%
- animated WebP
- cancel requests (via newly added `SDWebImageDownloadToken`)
- created `SDImageCacheConfig` class
- refactored duplicate code from all `WebCache` categories into a `UIView WebCache`category
- spot changes by comparing the old architecture to the new one: https://github.com/rs/SDWebImage/commit/d2f041b777caeb85a3856ff36f35d09cb78bc38c
- [4.0.0-beta changes](https://github.com/rs/SDWebImage/blob/master/CHANGELOG.md#400-beta---new-platforms-mac-os-x-and-watchos--refactoring-on-oct-5th-2016)
- [4.0.0-beta2 changes](https://github.com/rs/SDWebImage/blob/master/CHANGELOG.md#400-beta-2---new-platforms-mac-os-x-and-watchos--refactoring-on-oct-6th-2016)
- ...
### Migration guide
- still need to be written. [Draft](https://github.com/rs/SDWebImage/blob/master/Docs/SDWebImage-4.0-Migration-guide.md). [Ticket](https://github.com/rs/SDWebImage/issues/1590).
### Swift 3.0 support
- it seems there are some issues here, even though I could not reproduce them: [my demo project](https://github.com/rs/SDWebImage/files/515471/Swift3TestSDWebImage.zip). The [ticket link](https://github.com/rs/SDWebImage/issues/1627).

**Comment by bpoplauschi** [comment]
@mythodeia @rs @matej @lavoy @akhenakh 
@rromanchuk @mallorypaine @gsempe @mattjgalloway @timkoma @harishkashyap @tscheepers @voronianski
Guys, this is a very big release, we already have a working 4.0.0-beta2. I would really appreciate any help from you on testing or indicating missing parts before we can cut a final release.
I added the people I remembered being active on pull requests or conversations. Feel free to include other people if you know they can help.

**Comment by bpoplauschi** [comment]
+ @diejmon

**Comment by rs** [comment]
Looks great. In the migration draft, I don’t see the differrence between the 3 and 4 case. Isn’t it confusing?

**Comment by bpoplauschi** [comment]
@rs that section is still to be complete. I've listed all the changes and I just need the basic cases covered with examples.

**Comment by bpoplauschi** [comment]
@rs Also, I think the short description of SDWebImage points to an older documentation:http://hackemist.com/SDWebImage/doc. We can either update that (not sure how) or change that link to http://cocoadocs.org/docsets/SDWebImage, but only you can do this.

**Comment by rs** [comment]
Fixed.

**Comment by scottrhoyt** [comment]
Thanks for the great library, guys. It has saved me so much time over the years.

Just started a new Swift 3 project and using Carthage to install 4.0.0-beta2, I get the following build warning:

<img width="267" alt="screen shot 2016-10-11 at 12 08 47 pm" src="https://cloud.githubusercontent.com/assets/4259250/19284693/dd8304a4-8fab-11e6-92f8-33978d3b331b.png">

Everything is working fine--but I don't utilize the animated GIF support, so I'm not sure to what degree that is affected.

**Comment by nateboxer** [comment]
I'm trying to publish to itunesconnect (for TestFlight testing) and am getting these errors:

* This bundle is invalid. The value for key CFBundleShortVersionString '4.0.0-beta2' in the Info.plist file must be a period-separated list of at most three non-negative integers.

* This bundle Payload/.../SDWebImage.framework is invalid. The Info.plist is missing the required key: CFBundleVersion.

**Comment by skyline75489** [comment]
@nateboxer This makes sense because Apple doesn't allow any "beta" software uploaded.

**Comment by bpoplauschi** [comment]
All right guys, fingers crossed. I pushed the official 4.0.0 version.

**Comment by ivedeneev** [comment]
@bpoplauschi still getting error with "The Info.plist is missing the required key: CFBundleVersion.". any solutions?

**Comment by mythodeia** [comment]
@ivedeneev check [this](https://github.com/rs/SDWebImage/issues/1780)
