### ISSUE TITLE
why my app crash in [SDWebImageDownloaderOperation dealloc]  ?  

### ISSUE THREAD

**Issue by steven0610** [rs/SDWebImage#1716]
libobjc.A.dylib	objc_msgSend + 16
1 CoreFoundation	CFRelease + 524
2 CFNetwork	HTTPRequestParserClient::~HTTPRequestParserClient() + 52
3 CFNetwork	HTTPRequestMessage::~HTTPRequestMessage() + 80
4 CoreFoundation	CFRelease + 328
5 CFNetwork	URLRequest::~URLRequest() + 152
6 CoreFoundation	CFRelease + 328
7 CFNetwork	-[NSURLRequestInternal dealloc] + 40
8 CFNetwork	-[NSURLRequest dealloc] + 48
9 libobjc.A.dylib	object_cxxDestructFromClass(objc_object*, objc_class*) + 148
10 libobjc.A.dylib	objc_destructInstance + 92
11 libobjc.A.dylib	object_dispose + 28
12 Foundation	-[NSOperation dealloc] + 104
13 my app	-[SDWebImageDownloaderOperation dealloc] + 40
14 libsystem_blocks.dylib	_Block_release + 256
15 libdispatch.dylib	__dispatch_client_callout + 16
16 libdispatch.dylib	_dispatch_main_queue_callback_4CF + 1608
17 CoreFoundation	___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
18 CoreFoundation	___CFRunLoopRun + 1492
19 CoreFoundation	CFRunLoopRunSpecific + 396
20 GraphicsServices	GSEventRunModal + 168
21 UIKit	UIApplicationMain + 1488
22 my app	main (main.m:14)
23 libdyld.dylib	_start + 4

My SDWebImage version is the lasted in master .

There was nothing else in the log,could you please help me ? 
Thank you.

**Comment by steven0610** [comment]
And I also crash in the [SDWebImageDownloaderOperation cancelInternal],I think the 2 bug maybe the same problem.  

Could you please give me some issues. Thank you very much.



0	libobjc.A.dylib
objc_msgSend + 5
1	Foundation
+[NSConcreteNotification newTempNotificationWithName:object:userInfo:] + 119
2	Foundation
-[NSNotificationCenter postNotificationName:object:userInfo:] + 47
3	Foundation
-[NSNotificationCenter postNotificationName:object:] + 31
4	my app
___47-[SDWebImageDownloaderOperation cancelInternal]_block_invoke + 73
5	libdispatch.dylib
__dispatch_call_block_and_release + 11
6	libdispatch.dylib
__dispatch_client_callout + 23
7	libdispatch.dylib
_dispatch_main_queue_callback_4CF + 1532
8	CoreFoundation
___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
9	CoreFoundation
___CFRunLoopRun + 1591
10	CoreFoundation
CFRunLoopRunSpecific + 516
11	CoreFoundation
CFRunLoopRunInMode + 108
12	GraphicsServices
GSEventRunModal + 160
13	UIKit
UIApplicationMain + 144
14	my app
main (main.m:14)

**Comment by steven0610** [comment]
The reason of crash ,is here .    The crash is not happen usually,only  0.1%. 
But I think we must resove it.


Trapped fatal signal 'SIGSEGV(11)' ( "0 libobjc.A.dylib 0x00000001800d1b90 objc_msgSend + 16", "1 Foundation 0x00000001813428b4 0x000000018133c000 + 26804", "2 Foundation 0x00000001813427f0 0x000000018133c000 + 26608", "3  0x0000000100a5c5cc 0x0000000100040000 + 10601932", "4 libdispatch.dylib 0x00000001804a54bc 0x00000001804a4000 + 5308", "5 libdispatch.dylib 0x00000001804a547c 0x00000001804a4000 + 5244", "6 libdispatch.dylib 0x00000001804aab84 _dispatch_main_queue_callback_4CF + 1844", "7 CoreFoundation 0x0000000180a10d50 0x0000000180930000 + 920912", "8 CoreFoundation 0x0000000180a0ebb8 0x0000000180930000 + 912312", "9 CoreFoundation 0x0000000180938c50 CFRunLoopRunSpecific + 384", "10 GraphicsServices 0x0000000182220088 GSEventRunModal + 180", "11 UIKit 0x0000000185c22088 UIApplicationMain + 204", "12    my app 0x000000010044c280 0x0000000100040000 + 4244096", "13 libdyld.dylib 0x00000001804d68b8 0x00000001804d4000 + 10424" )

**Comment by steven0610** [comment]
I think there maybe some error ,when SD be used in UITableVIew, and much cancel action.  
But I did not find it.

**Comment by JamieScanlon** [comment]
I also Have this issue and also using the library in a UITableView. Triggered by a call to sd_cancelImageLoadOperationWithKey when i attempt to load an image in my cellForRowAtIndexPath method. Seems likely to do with cell reuse and canceling an operation from a reused cell.

**Comment by delox** [comment]
I'm having the same problem...

**Comment by bpoplauschi** [comment]
Those issues should be fixed in 4.0.0

**Comment by hejun-lyne** [comment]
Still have this issue in 4.0.0
Thread 0 (crashed)
 0  CoreFoundation!_CFRelease + 0x556
     r0 = 0x3744fb94    r1 = 0x1babd593    r2 = 0x00000000    r3 = 0x38363ab0
     r4 = 0x130ec994    r5 = 0x01601d80    r6 = 0x38362578    r7 = 0x01ba2bbc
     r8 = 0x00000124    r9 = 0x44d58a00   r10 = 0x01012480   r12 = 0x34c47edc
     fp = 0x130ec990    sp = 0x01ba2b88    lr = 0x1bdd5add    pc = 0x1b85c64a
    Found by: given as instruction pointer in context
 1  CFNetwork!HTTPRequestParserClient::~HTTPRequestParserClient() + 0x21
     r7 = 0x01ba2bc8    sp = 0x01ba2bc4    lr = 0x1bdd5add    pc = 0x1bdd5add
    Found by: previous frame's frame pointer
 2  CFNetwork!HTTPRequestParserClient::~HTTPRequestParserClient() + 0x21
     r7 = 0x01ba2bd8    sp = 0x01ba2bd0    lr = 0x1bf40b7d    pc = 0x1bdd5add
    Found by: previous frame's frame pointer
 3  CFNetwork!HTTPRequestMessage::~HTTPRequestMessage() + 0x37
     r7 = 0x01ba2c14    sp = 0x01ba2be0    lr = 0x1b85c299    pc = 0x1bf40b7d
    Found by: previous frame's frame pointer
 4  CoreFoundation!_CFRelease + 0x1a3
     r7 = 0x01ba2c24    sp = 0x01ba2c1c    lr = 0x1be6dddf    pc = 0x1b85c299
    Found by: previous frame's frame pointer
 5  CFNetwork!URLRequest::~URLRequest() + 0x6d
     r7 = 0x01ba2c60    sp = 0x01ba2c2c    lr = 0x1b85c299    pc = 0x1be6dddf
    Found by: previous frame's frame pointer
 6  CoreFoundation!_CFRelease + 0x1a3
     r7 = 0x01ba2c74    sp = 0x01ba2c68    lr = 0x1bf317f1    pc = 0x1b85c299
    Found by: previous frame's frame pointer
 7  CFNetwork!-[NSURLRequestInternal dealloc] + 0x1b
     r7 = 0x01ba2ca0    sp = 0x01ba2c7c    lr = 0x1ab19195    pc = 0x1bf317f1
    Found by: previous frame's frame pointer
 8  libobjc.A.dylib!objc_object::sidetable_release(bool) + 0xed
     r7 = 0x01ba2cb4    sp = 0x01ba2ca8    lr = 0x1bf32bfb    pc = 0x1ab19195
    Found by: previous frame's frame pointer
 9  CFNetwork!-[NSURLRequest dealloc] + 0x25
     r7 = 0x01ba2ce0    sp = 0x01ba2cbc    lr = 0x1ab19195    pc = 0x1bf32bfb
    Found by: previous frame's frame pointer
10  libobjc.A.dylib!objc_object::sidetable_release(bool) + 0xed
     r7 = 0x01ba2d00    sp = 0x01ba2ce8    lr = 0x1aafe047    pc = 0x1ab19195
    Found by: previous frame's frame pointer
11  libobjc.A.dylib!object_cxxDestructFromClass(objc_object*, objc_class*) + 0x73
     r7 = 0x01ba2d10    sp = 0x01ba2d08    lr = 0x1ab08ec5    pc = 0x1aafe047
    Found by: previous frame's frame pointer
12  libobjc.A.dylib!objc_destructInstance + 0x21
     r7 = 0x01ba2d1c    sp = 0x01ba2d18    lr = 0x1ab08ee5    pc = 0x1ab08ec5
    Found by: previous frame's frame pointer
13  libobjc.A.dylib!object_dispose + 0xd
     r7 = 0x01ba2d34    sp = 0x01ba2d24    lr = 0x1c0ef9a1    pc = 0x1ab08ee5
    Found by: previous frame's frame pointer
14  Foundation!-[NSOperation dealloc] + 0x59
     r7 = 0x01ba2d44    sp = 0x01ba2d3c    lr = 0x0054095b    pc = 0x1c0ef9a1
    Found by: previous frame's frame pointer
15  ourtimes + 0x53c959
     r7 = 0x01ba2d70    sp = 0x01ba2d4c    lr = 0x1ab19195    pc = 0x0054095b
    Found by: previous frame's frame pointer
16  libobjc.A.dylib!objc_object::sidetable_release(bool) + 0xed
     r7 = 0x01ba2d7c    sp = 0x01ba2d78    lr = 0x1af8fba7    pc = 0x1ab19195
    Found by: previous frame's frame pointer
17  libsystem_blocks.dylib!_Block_release + 0x81
     r7 = 0x01ba2d8c    sp = 0x01ba2d84    lr = 0x1af45083    pc = 0x1af8fba7
    Found by: previous frame's frame pointer
18  libdispatch.dylib!_dispatch_client_callout + 0x15
     r7 = 0x01ba2dd8    sp = 0x01ba2d94    lr = 0x1af495fd    pc = 0x1af45083
    Found by: previous frame's frame pointer
19  libdispatch.dylib!_dispatch_main_queue_callback_4CF + 0x379
     r7 = 0x01ba2de0    sp = 0x01ba2de0    lr = 0x1b85aa17    pc = 0x1af495fd
    Found by: previous frame's frame pointer
20  CoreFoundation!__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 0x7
     r7 = 0x01ba3a88    sp = 0x01ba2de8    lr = 0x1b858cff    pc = 0x1b85aa17
    Found by: previous frame's frame pointer
21  CoreFoundation!__CFRunLoopRun + 0x58d
     r7 = 0x01ba3b70    sp = 0x01ba3a90    lr = 0x1b7a8073    pc = 0x1b858cff
    Found by: previous frame's frame pointer
22  CoreFoundation!CFRunLoopRunSpecific + 0x1e5
     r7 = 0x01ba3b98    sp = 0x01ba3b78    lr = 0x1b7a7e81    pc = 0x1b7a8073
    Found by: previous frame's frame pointer
23  CoreFoundation!CFRunLoopRunInMode + 0x67
     r7 = 0x01ba3bb8    sp = 0x01ba3ba0    lr = 0x1cf54bfd    pc = 0x1b7a7e81
    Found by: previous frame's frame pointer
24  GraphicsServices!GSEventRunModal + 0x9b
     r7 = 0x01ba3bec    sp = 0x01ba3bc0    lr = 0x2096282f    pc = 0x1cf54bfd
    Found by: previous frame's frame pointer
25  UIKit!-[UIApplication _run] + 0x23d
     r7 = 0x01ba3c10    sp = 0x01ba3bf4    lr = 0x2095cf61    pc = 0x2096282f
    Found by: previous frame's frame pointer
26  UIKit!UIApplicationMain + 0x95
     r7 = 0x01ba3c28    sp = 0x01ba3c18    lr = 0x002a3fb5    pc = 0x2095cf61
    Found by: previous frame's frame pointer
27  ourtimes + 0x29ffb3
     r7 = 0x00000000    sp = 0x01ba3c30    lr = 0x1af7250b    pc = 0x002a3fb5
    Found by: previous frame's frame pointer
28  libdyld.dylib!start + 0x1
     r7 = 0x00000000    sp = 0x01ba3c30    lr = 0x00000000    pc = 0x1af7250b
    Found by: previous frame's frame pointer

**Comment by StarbuckBG** [comment]
Still happens 
![Uploading Screen Shot 2017-03-07 at 3.58.00 PM.png…]()

**Comment by StarbuckBG** [comment]
Still crashes
<img width="960" alt="screen shot 2017-03-07 at 3 58 00 pm" src="https://cloud.githubusercontent.com/assets/3859373/23659747/cbfd6b3a-034f-11e7-87b2-7629eafe66e8.png">

**Comment by chenzhuolin1002** [comment]
Still crashes in 4.0.0

**Comment by bpoplauschi** [comment]
@chenzhuolin1002 please provide detailed information about the crash. If it doesn't have the same stacktrace, please look at other issues on our project or create a new issue. It's important we keep the conversations on issues clean.

**Comment by bpoplauschi** [comment]
Ok, I will reopen this and look into it

**Comment by chenzhuolin1002** [comment]
@bpoplauschi Sorry, I forgot the crash stacktrace.
![image](https://cloud.githubusercontent.com/assets/995325/23894925/f2211124-08de-11e7-99e5-d707195a6b68.png)
Looks like the same issue.

**Comment by annamalairaj** [comment]
Getting crash very often. More than a 100 crashes in 60 days.

<img width="947" alt="screen shot 2017-05-18 at 1 28 02 pm" src="https://cloud.githubusercontent.com/assets/5246404/26192190/53d12978-3bce-11e7-88c4-4d81c3873720.png">

**Comment by Cooriyou** [comment]
I used v4.1 have a same crash

**Comment by steven0610** [comment]
A ho.  You take it,  I think you have to patch it in cancel and receaving data.

**Comment by justXyS** [comment]
0   CoreFoundation                	0x1e0320da _CFRelease + 1366
1   CFNetwork                     	0x1e5aa9ec HTTPRequestParserClient::~HTTPRequestParserClient() + 34
2   CFNetwork                     	0x1e72d704 HTTPRequestMessage::~HTTPRequestMessage() + 56
3   CoreFoundation                	0x1e031d28 _CFRelease + 420
4   CFNetwork                     	0x1e6535ae URLRequest::~URLRequest() + 110
5   CoreFoundation                	0x1e031d28 _CFRelease + 420
6   CFNetwork                     	0x1e71b590 -[NSURLRequestInternal dealloc] + 28
7   libobjc.A.dylib               	0x1d2f1194 objc_object::sidetable_release(bool) + 238
8   CFNetwork                     	0x1e71c99a -[NSURLRequest dealloc] + 38
9   libobjc.A.dylib               	0x1d2f1194 objc_object::sidetable_release(bool) + 238
10  libobjc.A.dylib               	0x1d2d6046 object_cxxDestructFromClass(objc_object*, objc_class*) + 116
11  libobjc.A.dylib               	0x1d2e0ec4 objc_destructInstance + 34
12  libobjc.A.dylib               	0x1d2e0ee4 object_dispose + 14
13  Foundation                    	0x1e8ed150 -[NSOperation dealloc] + 90
14  SDWebImage                    	0x0267797e -[SDWebImageDownloaderOperation dealloc]

**Comment by Robot2037** [comment]
The very same issue is bothering me too.

![screen shot 2017-06-25 at 21 29 41](https://user-images.githubusercontent.com/19485976/27519129-d2a5f7fa-59ed-11e7-91d9-acc64d9110ab.png)

**Comment by paulz** [comment]
```
Hardware Model:      iPhone7,1
Process:             OurApp [5738]
Path:                /private/var/containers/Bundle/Application/4D0FF6DF-21BF-4702-9023-112CA424F59D/OurApp.app/OurApp
Identifier:          com.omadahealth.OurApp
Version:             3 (2.4.1)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]


Date/Time:           2017-06-29 14:43:17.0516 -0700
Launch Time:         2017-06-29 14:43:13.3465 -0700
OS Version:          iPhone OS 10.1.1 (14B100)
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000c13b2bec8
Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [0]
Triggered by Thread:  0

Thread 0 name:
Thread 0 Crashed:
0   libobjc.A.dylib               	0x0000000187ef1704 objc_object::release() + 8 (objc-object.h:531)
1   CFNetwork                     	0x0000000189aac694 HTTPRequestParserClient::~HTTPRequestParserClient() + 52 (AutoTypes.h:29)
2   CFNetwork                     	0x0000000189c72c48 HTTPRequestMessage::~HTTPRequestMessage() + 84 (HTTPRequestMessage.cpp:38)
3   CoreFoundation                	0x000000018944da74 _CFRelease + 216 (CFRuntime.c:1891)
4   CFNetwork                     	0x0000000189b631f4 URLRequest::~URLRequest() + 168 (CFObject.h:220)
5   CoreFoundation                	0x000000018944da74 _CFRelease + 216 (CFRuntime.c:1891)
6   CFNetwork                     	0x0000000189c5f814 -[NSURLRequestInternal dealloc] + 40 (NSURLRequest.mm:75)
7   CFNetwork                     	0x0000000189c60b3c -[NSURLRequest dealloc] + 44 (NSURLRequest.mm:445)
8   libobjc.A.dylib               	0x0000000187ed6f10 object_cxxDestructFromClass(objc_object*, objc_class*) + 148 (objc-class.mm:462)
9   libobjc.A.dylib               	0x0000000187ee36e0 objc_destructInstance + 92 (objc-runtime-new.mm:6483)
10  libobjc.A.dylib               	0x0000000187ee3744 object_dispose + 28 (objc-runtime-new.mm:6502)
11  Foundation                    	0x0000000189ea1b20 -[NSOperation dealloc] + 92 (NSOperation.m:1113)
12  SDWebImage                    	0x00000001005921a4 -[SDWebImageDownloaderOperation dealloc] + 44 (SDWebImageDownloaderOperation.m:85)
13  libsystem_blocks.dylib        	0x000000018837ea28 _Block_release + 144 (runtime.c:175)
14  libdispatch.dylib             	0x00000001883291c0 _dispatch_client_callout + 16 (object.m:455)
15  libdispatch.dylib             	0x000000018832dd6c _dispatch_main_queue_callback_4CF + 1000 (inline_internal.h:2421)
16  CoreFoundation                	0x000000018944bf2c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12 (CFRunLoop.c:1793)
17  CoreFoundation                	0x0000000189449b18 __CFRunLoopRun + 1660 (CFRunLoop.c:3004)
18  CoreFoundation                	0x0000000189378048 CFRunLoopRunSpecific + 444 (CFRunLoop.c:3113)
19  GraphicsServices              	0x000000018adfe198 GSEventRunModal + 180 (GSEvent.c:2245)
20  UIKit                         	0x000000018f3642fc -[UIApplication _run] + 684 (UIApplication.m:2649)
21  UIKit                         	0x000000018f35f034 UIApplicationMain + 208 (UIApplication.m:4091)
22  OurApp                       	0x000000010008b390 main + 84 (main.m:7)
23  libdyld.dylib                 	0x000000018835c5b8 start + 4
```

**Comment by lianchengjiang** [comment]
The very same issue is bothering me too.
does anybody have solution？

**Comment by bpoplauschi** [comment]
Should be fixed by #1940 - closing for now

**Comment by bigbangvn** [comment]
Hi StarbuckBG,
How do you reproduce the crash?
