### ISSUE TITLE
Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior

### ISSUE THREAD

**Issue by vahids** [rs/SDWebImage#2248]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)

### Issue Info

 Info                    | Value                             
-------------------------|-------------------------------------|
 Platform Name            |ios 
 Platform Version        |11
 SDWebImage Version    |4.3.0
 Integration Method      |cocoapods
 Xcode Version           |Xcode 9.2 (9C40b)
 Repro rate              |all the time (100%)

### Issue Description and Steps

Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior warning 

![screenshot of xcode 17-12-1396 17-11-59](https://user-images.githubusercontent.com/1405424/37154003-dace0ea2-22f3-11e8-9551-c6a64abf0f3c.png)

**Comment by mythodeia** [comment]
this was fixed i think in https://github.com/rs/SDWebImage/pull/2242 & https://github.com/rs/SDWebImage/pull/2225

**Comment by vahids** [comment]
I updated to 4.3.2 but still have one warning:
`SDImageCache.m` on line 178

**Comment by bshirley** [comment]
It still appears, if in the build settings for pods:
(Xcode 9.4.1)
```
Apple LLVM 9.0 Warnings - Objective-C and ARC
Implicit retain of 'self' within blocks = YES
```
